### ISSUE TITLE
Add license to the repository

### ISSUE THREAD

**Issue by Miksuu** [ezbooz/Path-Of-Exile-2-RPC#1]
Could you add license (GPL or MIT?) to the repository?
I just tried this script and it works good on Linux after a minor edit to the script that doesn't break Windows functionality. If you add license to the repository, I could do a pull request later fixing this, also have some ideas to make it a little bit better. Thanks!

**Comment by ezbooz** [comment]
Hi, thanks for your feedback and willingness to help! I’ve added the MIT license. I really appreciate your contribution.
